"""empty message

Revision ID: 25c48a55f041
Revises: a8cc2736a43a
Create Date: 2022-09-08 15:32:47.939581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c48a55f041'
down_revision = 'a8cc2736a43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('header', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'header')
    # ### end Alembic commands ###
