"""empty message

Revision ID: 2eb5c39235d6
Revises: 5638e1bf404c
Create Date: 2022-08-31 07:43:59.338035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb5c39235d6'
down_revision = '5638e1bf404c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_terms', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_terms')
    # ### end Alembic commands ###
