"""empty message

Revision ID: 3574c8f82dec
Revises: 040d843f6fba
Create Date: 2022-09-01 14:32:15.033797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3574c8f82dec'
down_revision = '040d843f6fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'confirmed')
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.add_column('roles', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
